### PR TITLE
Fix console error for products without variants

### LINKED ISSUE #3349: Console error for products without variants
### Description

When you have a product with no variants, and you click on the product, the PDP may/may not load, and you get a browser console error.

(I discovered this issue while testing PR #3347)

### Expected behavior

When clicking on any product, the PDP of the product should load, and there should be no browser console errors.

### Actual behavior

When clicking on a product that has no variants, the PDP may/may not load, and you get the following browser console error:

```
TypeError: Cannot read property 'indexOf' of undefined
    at _variantIsSelected (products.js:84)
    at ReactiveDict.ReactionProduct.setProduct (products.js:169)
    at composer (productDetail.js:287)
    at tracker.js:37
    at Tracker.Computation._compute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339)
    at Tracker.Computation._recompute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:358)
    at Object.Tracker._runFlush (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:532)
    at onGlobalMessage (meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:398)
```

### Steps to reproduce the behavior

- Create a new product
- Go to your database and delete the variant instance of the new product
- Visit the product grid and click on the product created above
- Observe the browser console error above

### Versions

Node: 9.2.0
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.22.5
Reaction: 1.5.10
Reaction branch: joykare-product-validation-fix
Docker: 1.13.0

### PR DESCRIPTION
**Pull request by iakhator**
Resolve #3349 

PR resolve console error displayed when variant does not exist in the PDP. This actually happens because the product variant value is empty hence a check is placed to make sure variant exists before checking for `indexOf`

#### Test
- Create a new product
- Go to your database GUI and delete the variant instance of the new product
- Do not refresh the product grid page
- Visit the product grid and click on the product created above
- Observe the browser console to see no error displayed

### CODE REVIEW

File: lib/api/products.js [hunk 1]
```diff
@@ -81,11 +81,12 @@ export function applyProductRevision(product) {
  */
 export function variantIsSelected(variantId) {
   const current = ReactionProduct.selectedVariant();
-  if (current && typeof current === "object" && (variantId === current._id || ~current.ancestors.indexOf(variantId))) {
-    return true;
-  }
-
-  return false;
+  if (current.ancestors) {
```
Comment (zenweasel) [inline lib/api/products.js]: You've introduced a possible failure here because you are checking for `current.ancestors` before checking if `current` exists as is done below.

**Comment by iakhator** [comment]
I will always have this in mind. Thanks

**Comment by zenweasel** [comment]
Tested and it works, just wondering if we could simplify the code a little.

**Comment by iakhator** [comment]
alright, I will work on it
