### PR TITLE
feat: Product/Variant GQL fixes

### LINKED ISSUE #6066: GQL: Fix various issues with product queries and mutations
## Issue Description

Missing things

- [ ] variants/options resolver don't show hidden products
- [ ] `displayPrice` on the `pricing` field missing from variants and options
- [ ] missing media resolver for variants/options
- TBD (more missing will be added as implementation continues in the `reaction-admin`

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #6066   
Impact: **critical**  
Type: **feature|bugfix**

## Issue

There are some missing things for the product and variant GraphQL resolvers that make them difficult to use for administration.

- New variants are usually hidden. Variant resolvers only show visible, to its not possible to change this status unless you know the ID
- Media field is missing from the variants and options
- The media object is missing the ID field which is needed for deletions
- Some translations are missing for UI elements

## Solution

Add the missing things listed below:

- Allow for querying of hidden and archived variants.
- Add media resolver to `variants` and `options` resolvers
- Add missing `_id` field to `ImageInfo` type.
- Add missing translations

## Breaking changes

none

## Testing
Ensure integration tests pass and look good. 

**Note, Media is mocked because there is currently no mock in the test suite for it. Just making sure if media is present, no matter the mongo selector, that it does appear in the response with correct info.**

1. Query a product using the query below
1. Include `shouldIncludeHiddenVariants` and `shouldIncludeArchivedVariants` for some queries.
1. Remove `shouldIncludeHiddenVariants` and `shouldIncludeArchivedVariants`  for some queries. You should see both `hidden` and `visible` products, but not see any `archived/deleted` variants.
1. Repeat the above steps for `shouldIncludeHiddenOptions` and `shouldIncludeArchivedOptions`

Variables.

```js
{
  "productId": "<PRODUCT_ID>",
  "shopId": "<SHOP_ID>",
  "shouldIncludeHiddenVariants": true,
  "shouldIncludeArchivedVariants": false,
  "shouldIncludeHiddenOptions": true,
  "shouldIncludeArchivedOptions": false
}
```

Query
```graphql
query Product(
  $productId: ID!
  $shopId: ID!
  $shouldIncludeHiddenVariants: Boolean
  $shouldIncludeArchivedVariants: Boolean
  $shouldIncludeHiddenOptions: Boolean
  $shouldIncludeArchivedOptions: Boolean
) {
  product(
    productId: $productId
    shopId: $shopId
  ) {
    _id
    title
    media {
      _id
      URLs {
        small
        medium
        large
        thumbnail
      }
    }
    variants(
      shouldIncludeHidden: $shouldIncludeHiddenVariants,
      shouldIncludeArchived: $shouldIncludeArchivedVariants
    ) {
      _id
      title
      media {
        _id
        URLs {
          small
          medium
          large
          thumbnail
        }
      }
      options(
        shouldIncludeHidden: $shouldIncludeHiddenOptions,
        shouldIncludeArchived: $shouldIncludeArchivedOptions
      ) {
        _id
        title
        media {
          _id
          URLs {
            small
            medium
            large
            thumbnail
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

File: src/core-services/catalog/utils/getCatalogProductMedia.js [hunk 1]
```diff
@@ -27,6 +29,7 @@ export default async function getCatalogProductMedia(productId, collections) {
       const { priority, productId: prodId, variantId } = metadata || {};
 
       return {
+        _id: encodeOpaqueId("reaction/mediaRecord", media._id),
```
Comment (aldeed) [inline src/core-services/catalog/utils/getCatalogProductMedia.js]: We always encode IDs in the resolvers because some internal calls expect IDs to come back still internal. In `src/core/graphql/resolvers/index.js`, you can add a resolver for `ImageInfo._id`:

```js
import encodeOpaqueId from "@reactioncommerce/api-utils/encodeOpaqueId.js";

export default {
  ImageInfo: {
    _id: (node) => encodeOpaqueId("reaction/mediaRecord", node._id)
  },
  // other stuff
};
```

Plus then you can include the `_id` but remove the encoding from all other files that have it.

File: src/core-services/product/utils/getProductMedia.js [hunk 2]
```diff
@@ -29,6 +31,7 @@ export default async function getProductMedia(product, context) {
       const { priority, productId: prodId, variantId } = metadata || {};
 
       return {
+        _id: encodeOpaqueId("reaction/mediaRecord", media._id),
```
Comment (aldeed) [inline src/core-services/product/utils/getProductMedia.js]: Keep `_id` but leave the encoding for the resolver to do

File: src/core-services/product/utils/getVariantMedia.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+  );
+
+  // Denormalize media
+  const variantMedia = mediaArray
+    .map((media) => {
+      const { metadata } = media;
+      const { priority, variantId: variantIdLocal } = metadata || {};
+
+      return {
+        _id: encodeOpaqueId("reaction/mediaRecord", media._id),
```
Comment (aldeed) [inline src/core-services/product/utils/getVariantMedia.js]: Keep `_id` but leave the encoding for the resolver to do

File: src/core/graphql/schema.graphql [hunk 4]
```diff
@@ -60,6 +60,9 @@ type ImageInfo {
   "A list of URLs for various size files of this image"
   URLs: ImageSizes
 
+  "ID"
+  _id: ID!
+
```
Comment (aldeed) [inline src/core/graphql/schema.graphql:65]: I think making this field required may be problematic because this type is also used on `CatalogProduct` and `CatalogProductVariant` types, but they do not have IDs in the catalog collection.

**Review by aldeed — CHANGES_REQUESTED** [review]
Reviewed code only. I think a couple small things need to be adjusted.

File: src/core/graphql/schema.graphql (hunk 4 above)
Comment (mikemurray) [reply src/core/graphql/schema.graphql:65]: I removed the requirement for now just in case it does have an effect on catalog products and variants

**Comment by mikemurray** [comment]
@aldeed Addressed your comments

**Review by kieckhafer — CHANGES_REQUESTED** [review]
All visible / archived work looks good, coming across an issue with media though.

When I try to publish media via the `admin`, I get this error in the `api` server logs:
```
05:33:45.553Z ERROR Reaction: product.media.0._id is not allowed by the schema (errorId=ck68vmjtd00045ctnh2n5cvnd)
  path: [
    "publishProductsToCatalog"
  ]
  --
  stack: ClientError: product.media.0._id is not allowed by the schema
      at /usr/local/src/app/node_modules/simpl-schema/dist/SimpleSchema.js:635:21
      at Array.forEach (<anonymous>)
      at SimpleSchema.validate (/usr/local/src/app/node_modules/simpl-schema/dist/SimpleSchema.js:627:13)
      at publishProductToCatalog (file:///usr/local/src/app/src/core-services/catalog/utils/publishProductToCatalog.js:43:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
      at async Promise.all (index 0)
      at async publishProductsToCatalog (file:///usr/local/src/app/src/core-services/catalog/utils/publishProductsToCatalog.js:13:19)
      at async Object.publishProducts (file:///usr/local/src/app/src/core-services/catalog/mutations/publishProducts.js:44:19)
```

**Review by kieckhafer — APPROVED** [review]

**Review by manueldelreal — APPROVED** [review]
:shipit:
