### PR TITLE
Fixes #1537 - Alerts throwing error

### LINKED ISSUE #1537: Closing Sweet Alert modal (Alerts.alert) sometimes throws error
### Expected behavior

Not to have client errors when closing Alert boxes.
### Actual Behavior

When using a SweetAlert2 modal, closing it sometimes throws an error.  
If closing by clicking on the 'overlay' the error looks like 
`Uncaught (in promise) overlay`
image

If closing by timing out (use of timer setting such as `timer: 2500`):
`Uncaught (in promise) timer`
### Steps to Reproduce the Behavior

Create an Alert with settings similar to the following

```
Alerts.alert({
                title: "Nice!",
                text: "Testing!",
                type: "success",
                timer: 2500,
                showCancelButton: true,
              }, function () {
                console.log("confirmed!");
              });
```

Click outside of the alert card to dismiss it or allow the timer to dismiss the alert and you should see an error in the console.

This appears to be a known issue
https://github.com/limonte/sweetalert2/issues/177

PR on the way.

### PR DESCRIPTION
**Pull request by spencern**
Catch and silently handle errors thrown by SweetAlert2 such as `Uncaught (in promise) overlay` with lodash noop

### CODE REVIEW

**Comment by jshimko** [comment]
👍

File: imports/plugins/core/layout/client/templates/layout/alerts/reactionAlerts.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ Object.assign(Alerts, {
         if (isConfirm === true && typeof messageOrCallback === "function") {
           messageOrCallback(isConfirm);
         }
-      });
+      }).catch(_.noop);
```
Comment (spencern) [inline imports/plugins/core/layout/client/templates/layout/alerts/reactionAlerts.js]: Good thoughts. I've updated this code to catch/silence the three usual sweet alert errors and re-throw anything else.

**Comment by spencern** [comment]
@zenweasel I pushed a commit that addresses your concerns up a couple days ago but forgot to tag you in the comment.

**Comment by aaronjudd** [comment]
👍
