### PR TITLE
2422 Fix on email invite link leading to blank screen

### LINKED ISSUE #2422: Clicking on link in invite email leads to blank screen
### Expected behavior
Should receive create password screen

### Actual Behavior
Receive this dialog instead
reaction

### Steps to Reproduce the Behavior
1. Login as admin
1. Invite user with valid email
1. Open invitation email and visit link
1. Observe broken dialog

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.9.2
Reaction: 1.2.0
Reaction branch: development
Docker: 17.03.1-ce
```

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #2422 

**Testing**

- Clone this branch
- Login as admin
- Invite user with valid email
- Open invitation email and visit link
- Observe that the `Update Password` dialog is not broken

### CODE REVIEW

File: client/modules/accounts/components/passwordReset/updatePasswordOverlay.js [hunk 1]
```diff
@@ -19,14 +19,23 @@ class UpdatePasswordOverlay extends Component {
...
+      password: "",
+      showSpinner: true
     };
 
     this.handleFieldChange = this.handleFieldChange.bind(this);
     this.handleSubmit = this.handleSubmit.bind(this);
     this.handleCancel = this.handleCancel.bind(this);
   }
 
+  componentDidMount() {
```
Comment (zenweasel) [inline client/modules/accounts/components/passwordReset/updatePasswordOverlay.js]: Using `setTimeout` is considered bad practice and you really shouldn't be using it anywhere in the project, especially on UI programming.
