### PR TITLE
Fixes 3597: adding country code to phone number before sending SMS

### LINKED ISSUE #3597: Validate phone numbers with country codes for SMS
### Expected behavior

Phone numbers should be stored in a standard format so sending SMS messages do no result in an error.

### Actual behavior

Without the country code Nexmo fails to send SMS messages.

### Steps to reproduce the behavior

1. Sign up for a free Nexmo account
1. In the SMS setting panel, enter Nexmo API credentials and test `from` number
1. In user profile edit or add 1st address and enter your phone number without the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Observe error in terminal
1. In user profile edit or add 1st address and enter your phone number **with** the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Receive text message!!!

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.25.0
Reaction: 1.6.6
Reaction branch: master
Docker: 17.12.0-ce

### PR DESCRIPTION
**Pull request by Akarshit**
Resolves #3597   
Impact: minor  
Type: bugfix

## Issue
Country code was not added to the phone number, which resulted in SMS not being sent.

## Solution
First the input phone number is validated. If it already has the country code nothing is modified. If it doesn't we try to add the country code to it.

If there is some problem in the process, we try to send the SMS to the original number.
1. Sign up for a free Nexmo account
1. In the SMS setting panel, enter Nexmo API credentials and test `from` number
1. In user profile edit or add 1st address and enter your phone number without the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Receive text message
1. In user profile edit or add 1st address and enter your phone number **with** the country code.
1. Run `Meteor.call("sms/send", "TEST", Meteor.userId(), ReactionCore._shopId.get(), console.log.bind(console))`
1. Receive text message

### CODE REVIEW

**Comment by aaronjudd** [comment]
@jshimko status of the review of this issue?

File: imports/plugins/included/sms/server/methods/sms.js [hunk 1]
```diff
@@ -19,6 +20,18 @@ async function lazyLoadNexmo() {
   Nexmo = mod.default;
 }
 
+function formatPhoneNo(phone, country) {
```
Comment (spencern) [inline imports/plugins/included/sms/server/methods/sms.js]: jsdoc?

Comment (spencern) [reply imports/plugins/included/sms/server/methods/sms.js]: @Akarshit

File: package.json [hunk 2]
```diff
@@ -58,7 +58,7 @@
     "jquery-i18next": "^1.2.1",
     "later": "^1.2.0",
     "libphonenumber-js": "^1.0.24",
-    "lodash": "^4.17.5",
+    "lodash": "^4.17.4",
```
[the remark this answers is not in the document]
Comment (Akarshit) [reply package.json]: This wasn't in the original PR, messed it up while resolving conflicts. Fixing it.

File: imports/plugins/included/sms/server/methods/sms.js (hunk 1 above)
Comment (Akarshit) [reply imports/plugins/included/sms/server/methods/sms.js]: Adding it.

**Comment by Akarshit** [comment]
Will fix this by monday.

**Comment by Akarshit** [comment]
@jshimko Updated the PR.

File: imports/plugins/included/sms/server/methods/sms.js [hunk 3]
```diff
@@ -2,6 +2,7 @@ import { Meteor } from "meteor/meteor";
 import { check } from "meteor/check";
 import { Sms, Accounts } from "/lib/collections";
 import { Reaction, Logger } from "/server/api";
+import { parse, isValidNumber, getPhoneCode } from "libphonenumber-js";
```
[the remark this answers is not in the document]
Comment (Akarshit) [reply imports/plugins/included/sms/server/methods/sms.js]: Hmm, I am surprised why linter didn't caught that(still doesn't!).

File: imports/plugins/included/sms/server/methods/sms.js [hunk 4]
```diff
@@ -19,6 +20,25 @@ async function lazyLoadNexmo() {
...
+ */
+function formatPhoneNo(phone, country) {
+  try {
+    // phone no. already has the country code attached
+    if (isValidNumber(phone)) {
+      return phone;
+    }
+    // try attaching the country code to phone no.
+    return getPhoneCode(country) + parse(phone, country).phone;
+  } catch (error) {
```
[the remark this answers is not in the document]
Comment (Akarshit) [reply imports/plugins/included/sms/server/methods/sms.js]: The function is a best effort functions. So it tried to fetch the country code and add that to the phone number. But if it is not able to, it just returns the original number.

File: imports/plugins/included/sms/server/methods/sms.js [hunk 5]
```diff
@@ -66,8 +86,11 @@ Meteor.methods({
     const addressBook = user && user.profile ? user.profile.addressBook : false;
     // check for addressBook phone
     const phone = (Array.isArray(addressBook) && addressBook[0] && addressBook[0].phone) || false;
+    const country = (Array.isArray(addressBook) && addressBook[0] && addressBook[0].country) || false;
```
[the remark this answers is not in the document]
Comment (Akarshit) [reply imports/plugins/included/sms/server/methods/sms.js]: TBH I wasn't sure how addressBook works, I just copied the code from the line above. Looking into this now.

File: lib/api/helpers.js [hunk 6]
```diff
@@ -200,6 +201,26 @@ export function getSlug(slugString) {
...
+ */
+export function formatPhoneNo(phone, countryCode) {
+  try {
+    // phone no. already has the country code attached
+    if (isValidNumber(phone)) {
+      return phone;
+    }
+    // try attaching the country code to phone no.
+    return `${getPhoneCode(countryCode)}${parse(phone, countryCode).phone}`;
+  } catch (error) {
```
Comment (Akarshit) [inline lib/api/helpers.js]: @zenweasel asked how will the caller know that a error has occurred.
Answer -> This is a best effort function, so it tries to add the country code to the phone number, but if that is not possible it just returns the original number.

**Comment by Akarshit** [comment]
Updated everything, except for a remaining comment

File: lib/api/helpers.js (hunk 6 above)
Comment (zenweasel) [reply lib/api/helpers.js]: Not sure what is meant "best effort function" but I would say that we want to go with how people would [expect](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) a function to behave. And I would say that if I submit something that is not a phone number to a `formatPhoneNumber` function and it can't format it, I would expect an error, not to just get back my bad phone number untouched. To just do nothing and swallow the error seems like it's just asking for errors upstream when you try to submit it to SMS sending.

File: lib/api/helpers.js [hunk 7]
```diff
@@ -200,6 +201,26 @@ export function getSlug(slugString) {
...
 }
 
+/**
+ * formatPhoneNo
+ * @summary prepends country code to phone no. if required
+ * @param  {String} phone the original phone no.
+ * @param  {String} countryCode the country's code to which the phone no. belongs to
+ * @return {String} the phone no. with country extension.
+ */
+export function formatPhoneNo(phone, countryCode) {
```
Comment (zenweasel) [inline lib/api/helpers.js]: Let's not use the abbreviation PhoneNo but just use PhoneNumber

File: lib/api/helpers.js [hunk 8]
```diff
@@ -1,6 +1,7 @@
 import url from "url";
 import { Meteor } from "meteor/meteor";
 import { check } from "meteor/check";
+import { parse, isValidNumber, getPhoneCode } from "libphonenumber-js";
```
Comment (zenweasel) [inline lib/api/helpers.js]: Still import order (NPM imports before Meteor imports)

File: lib/api/helpers.js [hunk 9]
```diff
@@ -200,6 +201,26 @@ export function getSlug(slugString) {
   return slug;
 }
 
+/**
+ * formatPhoneNo
```
Comment (zenweasel) [inline lib/api/helpers.js]: I think this is supposed to be the `@name JSDoc`?

**Comment by Akarshit** [comment]
Updated.

File: lib/api/helpers.js [hunk 10]
```diff
@@ -200,6 +201,33 @@ export function getSlug(slugString) {
...
+      return phone;
+    }
+    const phoneNumber = parse(phone, countryCode).phone;
+    const countryExtension = getPhoneCode(countryCode);
+    if (phoneNumber && countryExtension) {
+      // try attaching the country code to phone number
+      return `${countryExtension}${phoneNumber}`;
+    }
+    throw new Meteor.Error("invalid-parameter", "Incorrect format for phone number.");
+  } catch (error) {
```
Comment (zenweasel) [inline lib/api/helpers.js]: Should we maybe put the actual error code in the error output since "Incorrect format for phone number" may not actually be the error here?

Comment (Akarshit) [reply lib/api/helpers.js]: Hmm, yes makes sense. Doing that.

**Comment by Akarshit** [comment]
@zenweasel replaced the hard coded message with actual error in the `catch` block.
