### PR TITLE
Fixes #3761: NavBar made only once

### LINKED ISSUE #3761: Clicking shop title/logo makes mobile navigaiton flash open & close
### Expected behavior
- In a mobile browser while on the homepage clicking the shop title/logo should do nothing.

*master*
master

### Actual behavior
- In a mobile browser while on the homepage clicking the shop title/logo makes mobile nav flash open and close.

*release 1.8.0*
release-1 8 0

### Steps to reproduce the behavior
- In mobile browser while on the homepage click the shop title/logo to see mobile nav flash open & close.

### Versions
```sh
Node: 9.4.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
```
This issue looks to only happen in Chrome. I'm not seeing it in Safari on iPhone or Firefox on Android

### PR DESCRIPTION
**Pull request by Akarshit**
Resolves #3761  
Impact: minor
Type: bugfix|performance

## Issue
The issue was that the `getComponent` call was making a new component everytime. So the whole component tree from NavBar was being made again.

## Solution
The components are now made in the constructor and are reused in the `render()` this cause the internal checks of React in deciding when to render something again work properly.

## Testing
1. In a mobile browser while on the homepage clicking the shop title/logo should do nothing.

## To really test
1. Before merging this PR
1. Add a `contructor()` or `componentWillUnmount()` [here](https://github.com/reactioncommerce/reaction/blob/release-1.8.0/imports/plugins/core/ui-navbar/client/components/navbar.js#L45)
1. Add a breakpoint inside the constructor/function
1. Click on the brand title on the homepage
1. The code will reach the breakpoint, which mean the component is made again.
1. Merge this PR
1. Again click on the brand title on the homepage
1. The control will not reach the breakpoint, which means the component was not made again.

### CODE REVIEW

File: imports/plugins/core/layout/client/components/coreLayout.js [hunk 1]
```diff
@@ -5,43 +5,61 @@ import { getComponent, registerComponent } from "@reactioncommerce/reaction-comp
...
+
+    if (footerComponent) {
+      this.footerComponent = React.createElement(footerComponent, {});
     }
   }
 
-  return (
-    <div className={pageClassName} id="reactionAppContainer">
+  render() {
+    const { actionViewIsOpen, structure } = this.props;
```
Comment (nnnnat) [inline imports/plugins/core/layout/client/components/coreLayout.js]: I feel like you could have the code from lines 28 - 46 live inside a lifecycle method (componentWillMount, componentWillUpdate) and only have the return inside the `render` method.

Comment (Akarshit) [reply imports/plugins/core/layout/client/components/coreLayout.js]: I thought that might be out of scope for this bug, but yes maybe it makes sense to move them now. 
Thanks :)

Comment (aaronjudd) [reply imports/plugins/core/layout/client/components/coreLayout.js]: @jshimko approved this so we're merging it, if that wasn't expected and @Akarshit @nnnnat  if this is worth doing please add the updates as a new PR.
