### PR TITLE
Fix on Console Errors when clicking order search results

### LINKED ISSUE #2569: Errors in console when clicking on Order Search results
### Expected behavior
No errors in console, order panel never opens

### Actual Behavior
Receive the following error in the console and the order panel never opens
```
Exception in template helper: TypeError: Cannot read property '_id' of undefined
    at Object.order (http://localhost:3000/app/app.js?hash=f70b791e1c8348b7524647313fe3374f96c34893:47820:26)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at http://localhost:3000/app/app.js?hash=f70b791e1c8348b7524647313fe3374f96c34893:46114:22
    at Blaze.View.<anonymous> (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:264:18)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20
```

### Steps to Reproduce the Behavior
1. Login as admin
1. Enable shipping and Stripe
1. Place an order
1. Go to home screen
1. Go to Search and select orders
1. Enter a search query that will bring up results (such as your email)
1. Click on the results
1. Observe the error and that the panel never opens

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.10.2
Reaction: 1.4.0
Reaction branch: master
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by rhenshaw56**
**Fixes #2569** 

**Testing**
- Login as admin
- Enable shipping and Stripe
- Place an order
- Go to home screen
- Go to Search and select orders
- Enter a search query that will bring up results (such as your email)
- Click on the results
- Observe that no error shows up in the console

### CODE REVIEW

**Comment by zenweasel** [comment]
This fixes the console error but it's sometimes pulling up the wrong order ID.

dashboard_orders

File: imports/plugins/included/ui-search/lib/containers/searchModalContainer.js [hunk 1]
```diff
@@ -272,9 +272,14 @@ function composer(props, onData) {
   Meteor.subscribe("ShopMembers");
   const siteName = getSiteName();
 
-  onData(null, {
-    siteName
-  });
+  const orderSub = Meteor.subscribe("Orders");
```
Comment (zenweasel) [inline imports/plugins/included/ui-search/lib/containers/searchModalContainer.js]: A shop might have tens of thousands of orders, we don't want to pull them all client-side as this will more than likely freeze the client and cause the app to be non-responsive. We've already seen cases where even pull a few hundred orders causes the browser to choke. We need to always be very cautious about what we decide to keep on the client.

**Comment by zenweasel** [comment]
@rhenshaw56 There's something still happening here. Try this:
1. Enter 3 orders
1. Click on the third order in the list (correct order is shown)
1. Close the order side panel (the part with the order detail)
1. Click on an order again
1. Observe that the order detail panel is empty

**Comment by rhenshaw56** [comment]
@zenweasel, i noticed that but i figured it was an isolated issue because same thing happens when you try to do the same on accounts search. I would look into it immediately.

**Comment by zenweasel** [comment]
@rhenshaw56 I verified that this a new issue introduced with this ticket and not happening on `master` outside of the search.

**Comment by rhenshaw56** [comment]
@zenweasel I've fixed the changes you requested.
