### PR TITLE
Don't break out orders with quantities

### LINKED ISSUE #2102: [Avalara] Don't break out order items
Currently the order items (**not** cart items) are "exploded" out, adding a new line item for every quantity (e.g. 30 X Item = 30 line items with a quantity of 1).

We want to change the behavior so that order items are kept as an aggregate until they are operated upon, e.g. split-shipped/returned etc. Then they should be broken out.

This change should be made in a backwards-compatible way so that people with existing orders don't experience any issues.

### PR DESCRIPTION
**Pull request by zenweasel**
Closes #2102 and resolves blocker with Avalara

Changes the behavior `copyCartToOrder` to not break out lines with quantities into individual lines

### To Test

This change should have no visibility to the user except for seeing new orders not broken out. The most important thing to test is that nothing is broken. With the exception for adding in some conditionals for Inventory hooks I didn't see any compatibility issues with moving forward from old versions.

### CODE REVIEW

File: imports/plugins/core/orders/client/templates/workflow/shippingInvoice.js [hunk 1]
```diff
@@ -495,43 +490,13 @@ Template.coreOrderShippingInvoice.helpers({
...
-          lineNumber: item.cartItemId
+          lineNumber: item._id
         });
         return _.extend(item, { taxDetail });
       });
     } else {
       items = returnItems;
     }
-
-    /**
```
Comment (aaronjudd) [inline imports/plugins/core/orders/client/templates/workflow/shippingInvoice.js]: We need more comments, not less.

File: imports/plugins/included/inventory/server/hooks/hooks.js [hunk 2]
```diff
@@ -112,9 +112,10 @@ function markInventoryShipped(doc) {
 function markInventorySold(doc) {
   const orderItems = doc.items;
   const cartItems = [];
+  // If a cartItemId exists it's a legacy order and we use that
   for (const orderItem of orderItems) {
     const cartItem = {
-      _id: orderItem.cartItemId,
+      _id: orderItem.cartItemId || orderItem._id,
```
Comment (aaronjudd) [inline imports/plugins/included/inventory/server/hooks/hooks.js]: Is this change / behaviour documented elsewhere? Should be added to release docs?
