### PR TITLE
[4333] Bug Fix: Marketplace Settings

### LINKED ISSUE #4333: Marketplace Settings Failing to Save
## Issue Description
Error Message:
Failed to save Marketplace settings Error: settings.shops.enabledShopTypes.0.active is not allowed by the schema

## Steps to Reproduce
1. Log into Primary Shop as admin@localhost
2. Enable Marketplace via Shop > Marketplace
3. Check [Allow merchant signup]

## Possible Solution
May just be a name change. Here is the Schema:
``` JavaScript
export const ShopTypes = new SimpleSchema({
  shopType: {
    type: String,
    defaultValue: "merchant"
  },
  enabled: {
    type: Boolean,
    defaultValue: false
  }
}, { check, tracker: Tracker });
```

### Versions
(run `reaction -v` from your reaction directory)
```
Node: 6.11.3
NPM: 3.8.6
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.12.0
Reaction branch: master
Docker: 17.09.0-ce
```

### PR DESCRIPTION
**Pull request by pmn4**
Resolves #4333  
Impact: **major**  
Type: **bugfix**

## Issue
It appears this bug has been here for some time. Not sure how it was not previously caught, but assuming the SimplSchema work uncovered it... not sure.

## Solution
s/`active`/`enabled` to match the schema.

## Testing
_see #4333 for repro steps_

### CODE REVIEW

File: imports/plugins/included/marketplace/lib/collections/schemas/marketplace.js [hunk 1]
```diff
@@ -64,10 +64,10 @@ export const MarketplacePackageConfig = PackageConfig.clone().extend({
     type: Array,
     defaultValue: [{
       shopType: "merchant",
-      active: true
+      enabled: true
```
Comment (pmn4) [inline imports/plugins/included/marketplace/lib/collections/schemas/marketplace.js]: [see the Schema definition above](https://github.com/reactioncommerce/reaction/pull/4334/files#diff-18f984780eed6839f9ac58fabffbe9dcR19)
