### PR TITLE
(fix): 3567 ESLint Rules (2)

### LINKED ISSUE #3567: Enable and fix eslint rules (2)
Uncomment the following rules in .eslintrc, run `npm run lint`, and fix all errors, either manually or using `eslint --fix`

block-spacing
computed-property-spacing
dot-location
function-paren-newline

### PR DESCRIPTION
**Pull request by joykare**
Resolves #3567 

This PR enables and fixes errors/warnings caused by:
- block-spacing
- computed-property-spacing
- dot-location
- function-paren-newline

**Note:** When **function-paren-newline** is enabled for React Components that are defined using some function e.g.
```
elements.push(
    <ListItem
         key={index}
         i18nKeyLabel={packageData.i18nKeyLabel}
         icon={packageData.icon}
         label={packageData.label}
         onClick={this.props.handleShowPackage}
         actionType="arrow"
         value={packageData}
     />
 );

OR

const component = shallow(
    <Translation
      defaultValue="Translated Text"
      i18nKey={"path.to.key"}
    />
);
```

return lint errors. Having them on one line leads to errors with `max-len` and creating new lines at other points returns a warning due to `react/jsx-closing-bracket-location`.

To fix this issue I've wrapped the components in parenthesis. Solution gotten from https://github.com/airbnb/javascript/issues/1584#issuecomment-341466143

```
const component = shallow((
    <Translation
      defaultValue="Translated Text"
      i18nKey={"path.to.key"}
    />
))
```

### CODE REVIEW

File: imports/plugins/core/accounts/client/components/permissionsList.js [hunk 1]
```diff
@@ -100,18 +100,16 @@ class PermissionsList extends Component {
...
-            label={permission.label}
-            actionType="switch"
-            switchOn={this.checked(permission.name)}
-            switchName={permission.name}
-            onSwitchChange={this.togglePermission(permission)}
-          />
-          {this.renderSubPermissions(permission)}
-        </div>
-      );
+      jsx.push(<div className="permission-item" key={`${permission.name}-${key}`}>
```
Comment (kieckhafer) [inline imports/plugins/core/accounts/client/components/permissionsList.js]: To me, this is more confusing having the `div` precedeced by the `jsx.push` on the same line.

File: imports/plugins/core/ui-tagnav/client/helpers/tags.js [hunk 2]
```diff
@@ -90,21 +90,19 @@ export const TagHelpers = {
       parentTagId = parentTag._id;
     }
 
-    Meteor.call("shop/updateHeaderTags", tagName, null, parentTagId,
-      function (error) {
-        if (error) {
-          Alerts.toast(i18next.t("productDetail.tagExists"), "error");
-        }
-      });
+    Meteor.call("shop/updateHeaderTags", tagName, null, parentTagId, function (error) {
```
Comment (kieckhafer) [inline imports/plugins/core/ui-tagnav/client/helpers/tags.js]: does this even need `function` here, or can we just go with `error`?

File: imports/plugins/core/ui-tagnav/client/helpers/tags.js [hunk 3]
```diff
@@ -90,21 +90,19 @@ export const TagHelpers = {
...
   },
 
   updateTag(tagId, tagName, parentTagId) {
-    Meteor.call("shop/updateHeaderTags", tagName, tagId, parentTagId,
-      function (error) {
-        if (error) {
-          Alerts.toast(i18next.t("productDetail.tagExists"), "error");
-        }
-      });
+    Meteor.call("shop/updateHeaderTags", tagName, tagId, parentTagId, function (error) {
```
Comment (kieckhafer) [inline imports/plugins/core/ui-tagnav/client/helpers/tags.js]: does this even need `function` here, or can we just go with `error`?

File: server/api/core/core.js [hunk 4]
```diff
@@ -519,8 +519,7 @@ export default {
     }, {
       fields: {
         language: 1
-      } }
```
Comment (kieckhafer) [inline server/api/core/core.js]: I feel like this is wrong to begin with...

Should it be:
```
    }
  });
```
now?

**Comment by kieckhafer** [comment]
Lint changes look good, made a few comments throughout, but my comments are on existing code, not new code, so this can be merged without addressing.
