### PR TITLE
Fix checkout login permissions

### LINKED ISSUE #2657: The arguments passed to userIsInRole() seems in the wrong order.
In master branch, release 1.4.0.
reaction/imports/plugins/core/checkout/client/templates/checkout/login/login.js
line 21:
const anonUser = Roles.userIsInRole(**"anonymous", Meteor.user()**, Reaction.getShopId());

According to the Role API document :
http://alanning.github.io/meteor-roles/classes/Roles.html#method_userIsInRole
_userIsInRole ( user  roles  [group] ) Boolean
Defined in roles/roles_common.js:254_

The order of 1st and 2nd argument should be reversed:
const anonUser = Roles.userIsInRole(**Meteor.user(), "anonymous"**, Reaction.getShopId());

The consequence of this issue is:  
   When I checkout without logged in and click "Continue as Guest" in first step, the  "Welcome, it's so good to see you." message will be displayed and go to 2nd step.(checkoutLoginCompleted returned true)

   If userIsInRole is invoked with correct argument order, the 1st step will keep its display and just go to 2nd step.(checkoutLoginCompleted returned false)

I am not sure which one is the expected behavior.

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2657 

### Steps to test
1. Checkout without logged in and click "Continue as Guest" in first step. The "Welcome, it's so good to see you." message will be displayed and go to 2nd step.(checkoutLoginCompleted returned true)
1. Checkout and Signin in the first step. The "Welcome, it's so good to see you." message will be displayed and go to 2nd step.(checkoutLoginCompleted returned true).

### CODE REVIEW

File: imports/plugins/core/checkout/client/templates/checkout/login/login.js [hunk 1]
```diff
@@ -17,10 +17,11 @@ Template.checkoutLogin.helpers({
     const cart = Cart.findOne();
     if (cart && cart.workflow) {
       const currentStatus = cart.workflow.status;
-      const guestUser = Reaction.hasPermission("guest", Meteor.user());
-      const anonUser = Roles.userIsInRole("anonymous", Meteor.user(), Reaction.getShopId());
+      const guestUser = Reaction.hasPermission("guest", Meteor.userId(), Reaction.getShopId());
+      const anonUser = Reaction.hasPermission("anonymous", Meteor.userId(), Reaction.getShopId());
 
-      if (currentStatus !== self.template && guestUser === true && anonUser === false) {
+      // when user is guest, they are also anonymous.
```
Comment (impactmass) [inline imports/plugins/core/checkout/client/templates/checkout/login/login.js]: Can you describe this better? i.e to explain what the check below it does?

Seeing `when user is guest, they are also anonymous` doesn't particular help a reader to understand why we do this check.

**Comment by impactmass** [comment]
Works as described in your steps. But when I register as a new user, the step 1 of checkout doesn't seem to recognize that someone is logged in. Can you confirm this?
screenshot 2017-08-28 14 19 29

File: imports/plugins/core/checkout/client/templates/checkout/login/login.js (hunk 1 above)
Comment (awadesmoline) [reply imports/plugins/core/checkout/client/templates/checkout/login/login.js]: @impactmass I have fixed the changes you requested, and updated the comments. Please confirm it works well now

**Comment by impactmass** [comment]
There's an error from the Circle CI tests. can you confirm why it failed?

**Comment by awadesmoline** [comment]
@impactmass they're passing now.

File: imports/plugins/core/checkout/client/templates/checkout/login/login.js [hunk 2]
```diff
@@ -17,10 +16,9 @@ Template.checkoutLogin.helpers({
     const cart = Cart.findOne();
     if (cart && cart.workflow) {
       const currentStatus = cart.workflow.status;
-      const guestUser = Reaction.hasPermission("guest", Meteor.user());
-      const anonUser = Roles.userIsInRole("anonymous", Meteor.user(), Reaction.getShopId());
+      const guestUser = Reaction.hasPermission("guest", Meteor.userId(), Reaction.getShopId());
```
Comment (aaronjudd) [inline imports/plugins/core/checkout/client/templates/checkout/login/login.js]: Don't need Meteor.userId() and getShopId(), those are supplied as default.

I worry about wether you should get rid of the permission check of "guest" and "anonymous".  I suspect this will have unexpected consequences in the `order/completed` page, and if you register a user in the Accounts UI-> not being in the checkout flow.

Comment (awadesmoline) [reply imports/plugins/core/checkout/client/templates/checkout/login/login.js]: I had to remove it because when clicking to continue as guest, the user still has the anonymous permission. So if we are checking to ensure that they are not anonymous, it fails. So that's why I just check if they are guest alone.

Comment (aaronjudd) [reply imports/plugins/core/checkout/client/templates/checkout/login/login.js]: When you click as "continue as guest" you ARE still `anonymous`.  you are only **NOT** anonymous if you have supplied an email, such as when you add an email at the order/completed stage.

Comment (awadesmoline) [reply imports/plugins/core/checkout/client/templates/checkout/login/login.js]: Yes that is how it is, but we were preventing `anonymous` from "continuing as guest". which is why I removed the permission for `anonymous`. I will retest and comment guest vs anonymous login view behavior as requested.

**Comment by awadesmoline** [comment]
@aaronjudd I updated the comments. Please take a look.

**Comment by aaronjudd** [comment]
See #2328 as well, may be related

**Comment by zenweasel** [comment]
@aaronjudd Is there more to do on this? Should I have someone else pick it up or are we close to merging?

**Comment by aaronjudd** [comment]
@rymorgan Note, while we closed this -> one side affect / repercussion -> the inline login in the checkout is supposed to show "REGISTER" as the default view, while the dropdown is supposed to show "SIGN IN" as the default view.

**Comment by rymorgan** [comment]
@aaronjudd Got it. I've made an issue to correct it. https://github.com/reactioncommerce/reaction/issues/2944
