### PR TITLE
Fixed Tax Cloud API not not loading tax codes on PDP

### LINKED ISSUE #2533: TaxCloud: Tax codes dropdown is empty after api configuration.
### Expected behavior
Tax codes from tax cloud should load into the `tax code` dropdown in the product detail page after the tax cloud API has been configured.

### Actual Behavior
This does not happen.

### Steps to Reproduce the Behavior
1. Start reaction
2. Configure taxcloud API
3. Access tax codes dropdown in product detail page

### Versions
(run `reaction -v` from your reaction directory)
???

[Updated 7/10/2017 by @spencern]

### PR DESCRIPTION
**Pull request by aanchirinah**
Resolves #2533

Tax Cloud API methods was not fetching the tax codes , so I added an `onSuccess` method in the Tax cloud Autoform hook to fetch tax codes.

##### HOW TO TEST 
- Configure Tax Cloud API
- Access tax codes dropdown from PDP

### CODE REVIEW

File: imports/plugins/included/product-variant/containers/variantFormContainer.js [hunk 1]
```diff
@@ -89,6 +89,21 @@ const wrapComponent = (Comp) => (
         }
       });
       const taxCodesArray = [];
+      // if (provider.name === "taxes-taxcloud") {
```
Comment (spencern) [inline imports/plugins/included/product-variant/containers/variantFormContainer.js]: Don't commit commented out code -

Comment (aanchirinah) [reply imports/plugins/included/product-variant/containers/variantFormContainer.js]: Fixed requested changes

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { Template } from "meteor/templating";
 import { AutoForm } from "meteor/aldeed:autoform";
 import { Packages } from "/lib/collections";
 import { Reaction, i18next } from "/client/api";
+import { Meteor } from "meteor/meteor";
```
Comment (zenweasel) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: Import order

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 3]
```diff
@@ -20,8 +21,21 @@ Template.taxCloudSettings.helpers({
 AutoForm.hooks({
   "taxcloud-update-form": {
     onSuccess: function () {
-      return Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
-        "success");
+      Meteor.call("taxcloud/getTaxCodes", (err, res) => {
+        if (err) {
+          throw new Meteor.Error(Number, "description");
```
Comment (zenweasel) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: Why are you are throwing a JS type as the first parameter to `Meteor.Error`?

Comment (aanchirinah) [reply imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: Will fix that , I was not sure the error code I wanted to use at that time so this is an oversight.

**Comment by kieha** [comment]
When I select a tax code from the drop-down I get this console error:

screen shot 2017-09-29 at 1 55 05 pm

**Comment by kieha** [comment]
I think you should safeguard against someone clicking the `Save Changes` button twice. I just clicked it twice and got this exception:

screen shot 2017-09-29 at 1 58 05 pm

THis happens because the DB is already populated with these values so when you click the `Save Changes` button again, it tried to populate the DB again with the same values, thus throwing the error.

**Comment by aanchirinah** [comment]
@kieha , I have fixed the requested changes and errors you experienced

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 4]
```diff
@@ -20,8 +22,23 @@ Template.taxCloudSettings.helpers({
 AutoForm.hooks({
   "taxcloud-update-form": {
     onSuccess: function () {
-      return Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
-        "success");
+      if (!TaxCodes.findOne({ taxCodeProvider: "taxes-taxcloud" })) {
+        Meteor.call("taxcloud/getTaxCodes", (err, res) => {
+          if (err) {
+            throw new Meteor.Error(500, "description");
```
Comment (spencern) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: We no longer recommend using number error codes. Also "description should be an actual description of the error.

The suggested template for errors is
```
throw new Meteor.Error("short-description", "Longer description")
```

E.g. 
```
throw new Meteor.Error("operation-failed", "client safe message about why")
```

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 5]
```diff
@@ -20,8 +22,23 @@ Template.taxCloudSettings.helpers({
...
+          } else if (res && Array.isArray(res)) {
+            Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
+              "success");
+            res.forEach((code) => {
+              Meteor.call("taxes/insertTaxCodes", Reaction.getShopId(), code, "taxes-taxcloud", (error) => {
+                if (error) {
+                  throw new Meteor.Error("Error populating TaxCodes collection", error);
```
Comment (spencern) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: This error uses a different format than your previous error.

As noted above, this will not alert the user via the UI, perhaps a Toast alert with the "error" style would be more appropriate here? I'm not too familiar with this tax plugin, so I'll defer to @zenweasel on what exactly the correct process is here.

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 6]
```diff
@@ -20,8 +22,23 @@ Template.taxCloudSettings.helpers({
 AutoForm.hooks({
   "taxcloud-update-form": {
     onSuccess: function () {
-      return Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
-        "success");
+      if (!TaxCodes.findOne({ taxCodeProvider: "taxes-taxcloud" })) {
+        Meteor.call("taxcloud/getTaxCodes", (err, res) => {
+          if (err) {
+            throw new Meteor.Error(500, "description");
+          } else if (res && Array.isArray(res)) {
```
Comment (spencern) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: I'm a bit skeptical that this code is doing what you want.

There are a few problems I want to point out:

1. You're toasting success here, and then looping through the responses and potentially throwing an error. It seems contradictory to alert the user of success if the error processing hasn't happened yet.

2. If you throw an error in this `forEach` loop, the loop will stop executing in the middle. You're not catching the error anywhere, and the error will not `toast` alert the user, it will just stop the app from continuing and log the error in the console.

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js (hunk 5 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: @spencern , thanks for pointing it out, I will fix it

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 7]
```diff
@@ -20,8 +22,27 @@ Template.taxCloudSettings.helpers({
...
+            Alerts.toast(
+              `${i18next.t("admin.taxSettings.shopTaxMethodsFailed")} ${err}`, "error"
+            );
+          } else if (res && Array.isArray(res)) {
+            Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
+              "success");
+            res.forEach((code) => {
+              Meteor.call("taxes/insertTaxCodes", Reaction.getShopId(), code, "taxes-taxcloud", (error) => {
+                if (error) {
+                  Alerts.toast(
```
Comment (spencern) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: This is better, but the issue of toasting success and then toasting failure remains

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js [hunk 8]
```diff
@@ -16,9 +16,9 @@ const taxCalc = {};
 
 taxCalc.getPackageData = function () {
   const pkgData = Packages.findOne({
```
Comment (aaronjudd) [inline imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: Is this the correct pattern here?

**Comment by spencern** [comment]
What's the status on this?

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 8 above)
Comment (zenweasel) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: I think we want to use `Reaction.getPackageSettings`?

**Comment by aanchirinah** [comment]
@spencern , fixing requested changes and pending reviews.

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 8 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: What is supposed to be the correct pattern? @aaronjudd

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js (hunk 7 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: So should I scrape the toast of failure inside `onSuccess` hook? @spencern

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js (hunk 6 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: I realised it wasn't necessary to be checking for errors while looping so I have refactored my code to work better.

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 8 above)
Comment (spencern) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: you should use the Reaction.getPackageSettings method:
https://github.com/reactioncommerce/reaction/blob/marketplace/server/api/core/core.js#L432

Comment (zenweasel) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: Also, is this change to Avalara required to make TaxCloud work? Something seems fishy?

Comment (aanchirinah) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: No it was to make Avalara work, and I have made the correct pattern change in my latest commit, @spencern @aaronjudd @zenweasel

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js [hunk 9]
```diff
@@ -15,11 +15,8 @@ const requiredFields = ["username", "password", "apiLoginId", "companyCode", "sh
 const taxCalc = {};
 
 taxCalc.getPackageData = function () {
-  const pkgData = Packages.findOne({
-    name: "taxes-avalara",
-    shopId: Reaction.getShopId(),
-    enabled: true
-  });
+  const pkgData = Reaction.getPackageSettings("taxes-avalara");
+  pkgData.settings.avalara = true;
```
Comment (zenweasel) [inline imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: Help me understand why we need to set a value in the package settings?

**Comment by zenweasel** [comment]
@aanchirinah Although I guess these test steps work, in the future I would like to see more detailed steps so that someone who is not super familiar with the project could be able to test it.

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 9 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: During my sync with @kieha , she made me aware the `enabled` boolean variable wasn't working properly and that `settings.avalara` is rather being used in the implementation of Avalara.

File: imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js [hunk 10]
```diff
@@ -20,8 +22,19 @@ Template.taxCloudSettings.helpers({
...
+          if (res && Array.isArray(res)) {
+            Alerts.toast(i18next.t("admin.taxSettings.shopTaxMethodsSaved"),
+              "success");
+            res.forEach((code) => {
+              Meteor.call("taxes/insertTaxCodes", Reaction.getShopId(), code, "taxes-taxcloud");
+            });
+          }
+        });
+      } else {
+        Alerts.toast("Taxcodes from Tax Cloud already loaded");
```
Comment (zenweasel) [inline imports/plugins/included/taxes-taxcloud/client/settings/taxcloud.js]: This needs a translation

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 9 above)
Comment (zenweasel) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: Do we need to open an issue to make this work correctly if we are working around a bug elsewhere? We don't just hack something and move on, we would expect a `TODO` item at least.

**Comment by zenweasel** [comment]
@aanchirinah You've introduced a lint error now that you need to resolve.

File: imports/plugins/included/taxes-avalara/server/methods/taxCalc.js (hunk 9 above)
Comment (aanchirinah) [reply imports/plugins/included/taxes-avalara/server/methods/taxCalc.js]: Duly noted, I would put a a `TODO` above it then

**Comment by zenweasel** [comment]
I fixed lint error and TODO comment so that we could go ahead and merge as it appears to work and fix this bug

**Comment by zenweasel** [comment]
@aanchirinah Actually it looks like we have failing tests

**Comment by stunjiturner** [comment]
I am using 1.13 reaction, when I use the dropdown, after selecting the taxable toggle. the dropdown is empty
