### PR TITLE
#3355 Fix event not defined in Firefox

### LINKED ISSUE #3355: "event is not defined" error in browser console in Firefox
### Expected behavior
No errors

### Actual behavior
Receive error in console
```
ReferenceError: event is not defined
[Learn More]
productGridItemsContainer.js:52:8
ProductGridItemsContainer/_this.onPageClick
productGridItemsContainer.js:52:8
<anonymous>
```

### Steps to reproduce the behavior

1. Launch Reaction with FF

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.23.1
Reaction: 1.5.11
Reaction branch: master
Docker: 17.09.0-ce
```

### PR DESCRIPTION
**Pull request by codejockie**
This PR fixes "event is not defined" error shown on the Firefox console.

## How to Test

1. Start reaction
2. Open the app on Firefox
3. Click on any part of the page
4. Observe in the console that no error is shown

Closes #3355

### CODE REVIEW

File: imports/plugins/included/product-variant/containers/productGridItemsContainer.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ const wrapComponent = (Comp) => (
       document.querySelector(".page > main").removeEventListener("click", this.onPageClick);
     }
 
-    onPageClick = () => {
+    onPageClick = (event) => {
```
Comment (pmn4) [inline imports/plugins/included/product-variant/containers/productGridItemsContainer.js]: is there a global `event` variable in Chrome? surprised this worked anywhere!

**Comment by pmn4** [comment]
looks good to me

File: imports/plugins/included/product-variant/containers/productGridItemsContainer.js (hunk 1 above)
Comment (codejockie) [reply imports/plugins/included/product-variant/containers/productGridItemsContainer.js]: The `event` object is always available when an event takes place in the browser.
