### PR TITLE
Order data fetch 

### LINKED ISSUE #2837: Selecting filtered orders not working properly
### Expected behavior

When there's a filter applied to the orders table and `select all` action performed, only the filtered orders should be selected.

### Actual Behavior

Even with a filter applied, `select all` selects all orders present in the table.

### Steps to Reproduce the Behavior

- Have a couple of orders in different states/stages
- Visit the orders dashboard (click on the orders icon in the sidebar)
- Apply any kind of filter to the orders e.g. search, paginate, filter by status
- Click `Select All` checkbox on order table header
- Observe that all the orders in the table are selected

### Versions
Node: 6.2.2
NPM: 3.10.9
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 1.13.0

### PR DESCRIPTION
**Pull request by joykare**
Resolves #2837 #2952 #2768

### Expected behavior

When there's a filter applied to the orders table and `select all` action performed, only the filtered orders should be selected.

### Actual Behavior
Even with a filter applied, `select all` selects all orders present in the table.

### How to test
- Have a couple of orders in different states/stages
- Visit the orders dashboard (click on the orders icon in the sidebar)
- Apply any kind of filter to the orders e.g.  filter by status
- Click Select All checkbox on order table header
- Change filters observe that only the filtered orders are selected

### Expected behavior

Orders table should have the same number of rows as orders.
For example: If there are two orders, have just two rows displayed.

### Actual Behavior
Extra empty rows appear even when there are orders.

### How to test
- Create two.more orders
- Open order dashboard, observe that table grows/shrinks depending on the number of orders
- If there are no results the default 3 rows show up

### Problem
Order Dashboard Table was using ReactTable's way of passing publication/collection as opposed to passing it the actual data

### How to test 
- Look through code, see that Order Table passes its own data to the React Table implementation.

### CODE REVIEW

File: imports/plugins/core/orders/client/containers/orderTableContainer.js [hunk 1]
```diff
@@ -0,0 +1,686 @@
...
+        <Comp
+          {...this.props}
+          handleSelect={this.handleSelect}
+          handleClick={this.handleClick}
+          displayMedia={this.handleDisplayMedia}
+          selectedItems={this.state.selectedItems}
+          selectAllOrders={this.selectAllOrders}
+          multipleSelect={this.state.multipleSelect}
+          setShippingStatus={this.setShippingStatus}
+
```
Comment (kieckhafer) [inline imports/plugins/core/orders/client/containers/orderTableContainer.js]: Remove this space here

**Comment by joykare** [comment]
@kieckhafer fixed

**Comment by kieckhafer** [comment]
Looks good!

cart_completed
