### PR TITLE
Fix for "Changing user currency does not update prices"

### LINKED ISSUE #3833: Changing user currency does not update prices
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Changing user currency is not updating prices.

This is not an issue with reactivity, the prices stay in USD when refreshing as well.
It does not appear to be a permissions issue, as being logged in as an admin does not resolve this issue.

## Steps to Reproduce
1. Start the app
2. Change user currency to something other than USD

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.1
Reaction branch: master
Docker: 17.12.0-ce
```

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #3833  
Impact: **critical**  
Type: **bugfix**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it. This may differ from the original ticket as you now have more information at your disposal.

## Solution
Changes:
Seems not possible to have a job that's scheduled via later.js to have
started immediately. Tried with delay() and after(), but no avail.

The solution was to just schedule a one-off task whenever the server
starts.

Also I did refactor the import of later.js , because it was not
consistently. Sometimes it was required directly, sometimes via
`Jobs.later`

## Breaking changes
none expected

## Testing
1. Reset the database
2. Start server
3. The currency exchange rates should be fetched immediately (or very short after spinning up the server)
4. Try to change the currency in the nav bar
5. Prices should change

### CODE REVIEW

**Comment by spencern** [comment]
@jshimko as this is an `impact-critical` issue, would you prioritize it above other non critical reviews?

**Comment by jshimko** [comment]
@spencern Yep.  Looking at it now.

File: imports/plugins/included/jobcontrol/server/jobs/exchangerates.js [hunk 1]
```diff
@@ -22,13 +22,23 @@ export function setupFetchFlushCurrencyHooks() {
...
         .save({
           // Cancel any jobs of the same type,
           // but only if this job repeats forever.
           cancelRepeats: true
         });
+
+      // Run the first time immediately after server start. The repeat({schedule}) option via
+      // later.js scheduling won't run before the first scheduled time, even with delay() or after()
+      new Job(Jobs, "shop/fetchCurrencyRates", {})
+        .priority("normal")
```
Comment (jshimko) [inline imports/plugins/included/jobcontrol/server/jobs/exchangerates.js]: Not a big deal, but `.priority("normal")` is the default, so this is redundant/unnecessary to have here.

Comment (jshimko) [inline imports/plugins/included/jobcontrol/server/jobs/exchangerates.js]: If we're going to standardize on the version of `later` included with the job queue package, we should probably remove the one from Reaction's package.json.  Since `@reactioncommerce/job-queue` is now on npm and [already has `later` defined as a dependency](https://github.com/reactioncommerce/reaction-job-queue/blob/master/package.json#L27), we shouldn't need to require `later` again and inject that dependency [here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/job-collection/lib/index.js#L6-L8) (right @mikemurray?).  But that's outside the scope of this issue and probably needs an issue to be filed over at https://github.com/reactioncommerce/reaction-job-queue.  Either way, I deleted `later` from Reaction's `package.json` and confirmed everything still works.  It was only used for the jobs and the job queue package installs it for you already, so I think you can safely remove it in this PR.

Otherwise, I can confirm that the fix works, so I think we're good to go.  @mikemurray can you just confirm how that `later` stuff is being handled in the npm package?  Did you do that dependency injection to solve some kind of issue?

**Comment by jshimko** [comment]
If we're going to standardize on the version of `later` included with the job queue package, we should probably remove the one from Reaction's package.json.  Since `@reactioncommerce/job-queue` is now on npm and [already has `later` defined as a dependency](https://github.com/reactioncommerce/reaction-job-queue/blob/master/package.json#L27), we shouldn't need to require `later` again and inject that dependency [here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/job-collection/lib/index.js#L6-L8) (right @mikemurray?).  But that's outside the scope of this issue and probably needs an issue to be filed over at https://github.com/reactioncommerce/reaction-job-queue.  Either way, I deleted `later` from Reaction's `package.json` and confirmed everything still works.  It was only used for the jobs and the job queue package installs it for you already, so I think you can safely remove it in this PR.

Otherwise, I can confirm that the fix works, so I think we're good to go.  @mikemurray can you just confirm how that `later` stuff is being handled in the npm package?  Did you do that dependency injection to solve some kind of issue?

**Comment by mikemurray** [comment]
@jshimko Later.js is not currently used in the npm package, though it is in the `package.json` to ensure it gets included. It was dependency injected into the package from Reaction. An update would need to be made in the `@reactioncommerce/job-queue` package use the npm version of later, rather than depending on dependency injection.

**Comment by prinzdezibel** [comment]
@jshimko removed the `priority("normal")`

File: imports/plugins/included/jobcontrol/server/jobs/exchangerates.js (hunk 1 above)
Comment (prinzdezibel) [reply imports/plugins/included/jobcontrol/server/jobs/exchangerates.js]: done

**Comment by prinzdezibel** [comment]
@mikemurray That means `Jobs.later` would be the right way to refer to it, correct?

**Comment by jshimko** [comment]
The job queue package makes sure it's in the `node_modules` dir, so the `require("later")` works whether Reaction declares it as a dependency or not.  We'll have to create a new issue in the other repo to clean it up, but it's not an emergency.  It's only installed once anyway since they both refer to the same version.

**Comment by mikemurray** [comment]
@prinzdezibel you could use `Jobs.later`, it's just a reference to the imported `later` so you could always just import and use later if needed.
