### PR TITLE
Fix Exception in delivering result of invoking 'email/verifySettings'

### LINKED ISSUE #2464: Exception in delivering result of invoking 'email/verifySettings'
Open email settings in dashboard, update settings, close the dashboard panel, view browser console:

```Exception in delivering result of invoking 'email/verifySettings': Error: Tyring set data after component(Container(EmailConfig)) has unmounted.
    at onData (http://localhost:3000/packages/modules.js?hash=324c20e0822d5dd5972b7d40d96a63c0b55798e8:18970:21)
    at http://localhost:3000/app/app.js?hash=35ec44c0610a5ab62f80750be4a4e4201baed3fd:72691:18
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=27829e936d09beae3149ecfbf3332c42ccb1596f:1105:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3678:12)
    at MethodInvoker.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3698:10)
    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:4816:9)
    at onMessage (http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:3525:206)
    at http://localhost:3000/packages/ddp-client.js?hash=c9ca22092a3137a7096e8ab722ba5ab8eedb9aec:2908:9
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:11)
```

Node: 7.5.0
NPM: 5.0.0
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: updated-packages-1.3.1
Docker: 17.03.1-ce

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2464

### Steps to test
1. Sign in as admin
1. Open email settings on the dashboard and update settings
1.  Close the dashboard panel
1.  Observe that there is no error on the console

### CODE REVIEW

File: imports/plugins/core/email/client/components/emailConfig.js [hunk 1]
```diff
@@ -17,6 +20,21 @@ class EmailConfig extends Component {
...
+      Meteor.call("email/verifySettings", (error) => {
+        if (error) {
+          this.setState({ status: "error", error: error.reason });
+        }
+        this.setState({ status: "valid", error: null });
+      });
+    } else {
+      this.setState({ status: "error", error: null });
+    }
+  }
```
Comment (jshimko) [inline imports/plugins/core/email/client/components/emailConfig.js]: This kind of logic should not be in a UI component.  Data retrieval and/or interaction with the server should always be done in the container component and then results passed into the UI component.  The UI component should only have markup and interactivity handling (`onClick`, etc).

Comment (awadesmoline) [inline imports/plugins/core/email/client/components/emailConfig.js]: Okay. Will change it. Thanks

Comment (awadesmoline) [inline imports/plugins/core/email/client/components/emailConfig.js]: @jshimko I have moved the method call to the container component.

**Comment by zenweasel** [comment]
@jshimko Can we get a review of this?

File: imports/plugins/core/email/client/containers/emailConfig.js [hunk 2]
```diff
@@ -1,38 +1,75 @@
+import React, { Component } from "react";
 import { useDeps } from "react-simple-di";
 import getServiceConfig from "nodemailer-wellknown";
 import { Meteor } from "meteor/meteor";
+import PropTypes from "prop-types";
```
Comment (zenweasel) [inline imports/plugins/core/email/client/containers/emailConfig.js]: Import order

File: imports/plugins/core/email/client/containers/emailConfig.js [hunk 3]
```diff
@@ -1,38 +1,75 @@
...
+  componentWillMount() {
+    const { settings } = this.props;
     const { service, host, port, user, password } = settings;
 
-    // if all settings exist, check if they work
     if (service && host && port && user && password) {
       Meteor.call("email/verifySettings", (error) => {
         if (error) {
-          return onData(null, { settings, status: "error", error: error.reason });
+          this.setState({ status: "error" });
```
Comment (zenweasel) [inline imports/plugins/core/email/client/containers/emailConfig.js]: So we aren't using the data from `error` any more?

**Comment by zenweasel** [comment]
This fixes the error and I fixed the import order so I am good with this one as long as @jshimko signs off on the implementation of his review.

File: imports/plugins/core/email/client/containers/emailConfig.js (hunk 3 above)
Comment (awadesmoline) [inline imports/plugins/core/email/client/containers/emailConfig.js]: @zenweasel it wasn't being used before.

Comment (zenweasel) [inline imports/plugins/core/email/client/containers/emailConfig.js]: Yeah, it should be but that's not what this ticket is about so that's why I already approved it.
