### PR TITLE
Fix Product Not Found infinite spinner

### LINKED ISSUE #1630: When visiting the URL for an archived product, receive endless spinner
### Expected behavior
Receive some sort of "product could not be found" message

### Actual Behavior
Just a white page with an endless spinner

### Steps to Reproduce the Behavior
1. Archive a product and publish the change
1. Visit the url for the product
1. Observe the endless spinner

### PR DESCRIPTION
**Pull request by kieckhafer**
Fixes #1630

PDP was displaying an infinite spinner if there was no product at the URL. This fix converts our old Product Not Found page to a React Component and displays when it should.

### CODE REVIEW

File: imports/plugins/included/product-detail-simple/client/components/productNotFound.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import React from "react";
+import { Translation } from "/imports/plugins/core/ui/client/components";
+import { TranslationProvider } from "/imports/plugins/core/ui/client/providers";
+
+const ProductNotFound = (props) => {
+  return (
+    <TranslationProvider>
+      <div className="container-fluid-sm">
+        <div className="empty-view-message">
+          <i className="fa fa-barcode"></i>
```
Comment (mikemurray) [inline imports/plugins/included/product-detail-simple/client/components/productNotFound.js]: must self close if empty `<i className="fa fa-barcode" />`

File: imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js [hunk 2]
```diff
@@ -5,11 +5,12 @@ import { ReactionProduct } from "/lib/api";
 import { Reaction, i18next, Logger } from "/client/api";
 import { Tags, Media } from "/lib/collections";
 import { Loading } from "/imports/plugins/core/ui/client/components";
-import { ProductDetail } from "../components";
+import { ProductDetail, ProductNotFound } from "../components";
 import { SocialContainer, VariantListContainer } from "./";
 import { MediaGalleryContainer } from "/imports/plugins/core/ui/client/containers";
 import { DragDropProvider, TranslationProvider } from "/imports/plugins/core/ui/client/providers";
 import { StyleRoot } from "radium";
+import { isEmpty } from "lodash";
```
Comment (zenweasel) [inline imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js]: Shouldn't this import go first?
