### PR TITLE
Always grab shipping from primary shop regardless of current shop (Resolves #2732/#2713)

### LINKED ISSUE #2732: [Marketplace] Shipping methods don't show up when checking out in non-primary shop
**Note** I am not 100% clear on what are the valid use cases here. This is checking out on a second shop as Marketplace admin, but that's the only way you can see product from both Primary and non-Primary shops.

### Expected behavior
Shipping methods should show up

### Actual Behavior
They don't. If you switch to primary shop, they do

### Steps to Reproduce the Behavior
1. Full reset. Once you successfully check out it appears (?) it never happens again
1. Set up a second shop and add a product
1. As marketplace admin switch to the second shop
1. Place an item in your cart
1. Attempt to check out
1. Observe that you receive the "Shipping method not configured" error and the Shipping config window opens but is broken (which it shouldn't even be there).
1. Switch back to Reaction and re-save your address.
1. Observe shipping method now appear

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by zenweasel**
Resolves #2732 and #2713 

### Steps to Test
1. Full reset.
1. Set up a second shop and add a product as shop admin
1. Try to checkout as shop admin. Observe that shipping methods appear
1. As marketplace admin switch to the second shop
1. Place an item in your cart
1. Attempt to check out
1. Observe that the shipping methods appear

### CODE REVIEW

**Comment by zenweasel** [comment]
Also resolves #2669 (which is a dupe)

**Comment by spencern** [comment]
We could make this conditional based on the [`merchantShippingRates` flag in marketplace](https://github.com/reactioncommerce/reaction/blob/marketplace/imports/plugins/included/marketplace/register.js#L61). That's how we'll need to do this once we permit each shop to define their own shipping options.

Since this does fix those issues and we're not ready to introduce that functionality yet, I'm going to add a TODO so that we remember to update this when we permit different shipping options per shop.

File: imports/plugins/core/shipping/client/templates/checkout/shipping.js [hunk 1]
```diff
@@ -65,7 +66,8 @@ Template.coreCheckoutShipping.onCreated(function () {
   const shippingOpts = {
     provides: "settings",
     name: "settings/shipping",
-    template: "shippingSettings"
+    template: "shippingSettings",
+    shopId: Reaction.getPrimaryShopId()
```
Comment (spencern) [inline imports/plugins/core/shipping/client/templates/checkout/shipping.js]: Could this potentially permit a non-marketplace-owner to adjust the shipping settings for marketplace or does it just prevent the other shipping settings apps from showing up? 
AFAIK they shouldn't have been showing up anyway because they would be disabled, but these changes seem to indicate differently.

Comment (zenweasel) [reply imports/plugins/core/shipping/client/templates/checkout/shipping.js]: That's a good question. They only show up when you get the "No shipping methods configure. Configure now" with the link. Ideally this should only show up when you actually have the permissions to modify the shipping settings which is currently if you are a shop admin correct? But it's only currently checking for `["owner", "admin"]);`

I wonder if we can't make this only show up when you actually have permissions to configure shipping? i.e. are Marketplace Admin?

Comment (zenweasel) [reply imports/plugins/core/shipping/client/templates/checkout/shipping.js]: For now, I can just back out that change, and we can deal with that separately?

Comment (spencern) [reply imports/plugins/core/shipping/client/templates/checkout/shipping.js]: Yeah, I'm testing, I'll test with and without that, and approve one way or the other
