### PR TITLE
Fix variant view in grid product layout

### LINKED ISSUE #2715: [Marketplace] Variant view in the grid product layout
When selecting the "variant" layout on a product in the grid (the middle option), we should be seeing the images and variants of the top 3 items from the product. Instead, nothing is happening, looks the same as the default layout. Related to #2647 

reaction

## version
Node: 6.11.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: awa-fix-variant-images (marketplace)
Docker: 17.06.0-ce

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2715

### Steps to test
1. Edit a product and add images for variants
1. On the product grid, select product and choose variant view
1. Observe that images for the top three variants are displayed as below
screen shot 2017-08-24 at 3 44 34 pm

### CODE REVIEW

File: imports/plugins/included/product-variant/containers/productGridItemsContainer.js [hunk 1]
```diff
@@ -126,12 +126,13 @@ const wrapComponent = (Comp) => (
...
     additionalProductMedia = () => {
+      const variants = ReactionProduct.getVariants(this.props.product._id);
+      const variantIds = variants.map(variant => variant._id);
       const mediaArray = Media.find({
         "metadata.productId": this.props.product._id,
-        "metadata.priority": {
-          $gt: 0
-        },
-        "metadata.toGrid": 1
+        "metadata.variantId": {
```
Comment (zenweasel) [inline imports/plugins/included/product-variant/containers/productGridItemsContainer.js]: Do we need to make sure these are not unpublished or archived?

**Comment by awadesmoline** [comment]
@zenweasel done.
