### PR TITLE
#3437 Fix can't set brand image for shop

### LINKED ISSUE #3437: Can't set brand image for shop
### Expected behavior
Shop admins should be able to add/set their brand image/logo for their shop

### Actual behavior
Shop admin sees all images (shouldn't, just theirs) and can delete all images (shouldn't, just theirs) but cannot set the image for their shop

### Steps to reproduce the behavior
1. Upload a brand image on main shop
1. Create a shop
1. Login as shop admin. Go to "Shops" and try try to set your shop image
1. Observe that you can't

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.3
Reaction branch: master
Docker: 17.09.1-ce
```

### PR DESCRIPTION
**Pull request by codejockie**
This PR fixes issues where a market shop owners can't upload their brand image and always see the primary shop's brand image if set on the primary shop.

## How to Test

1. Upload a brand image on main shop
2. Create a shop
3. Login as shop admin
4. Observe that you don't see the brand image set on the main shop
5. Go to "Shops" and try to set your shop image
6. Observe that you can now set shop image

Closes #3437

### CODE REVIEW

**Comment by zenweasel** [comment]
@codejockie When I set the brand image in the shop, it says"shopBrandAssetsSaved" but the image never shows as set (checkbox checked), and it never appears as the brand image.

File: imports/plugins/core/dashboard/client/templates/shop/settings/settings.js [hunk 1]
```diff
@@ -76,12 +76,16 @@ Template.shopSettings.helpers({
     return "";
   },
   brandImageSelectProps() {
+    const shopId = Reaction.getShopId();
+
     const media = Media.find({
+      "metadata.ownerId": Meteor.userId(),
```
Comment (pmn4) [inline imports/plugins/core/dashboard/client/templates/shop/settings/settings.js]: would this limit the query to only those that the current user uploaded?

Comment (codejockie) [reply imports/plugins/core/dashboard/client/templates/shop/settings/settings.js]: @pmn4, that's what it does.

Comment (pmn4) [reply imports/plugins/core/dashboard/client/templates/shop/settings/settings.js]: ok, got it.
this is a super minor scenario, but do you think this could be an issue in shops with multiple admins? i.e., what if I mistakenly change the brand image and want to get it back to the image that you uploaded? I would have to ask you to change it back, right?

Comment (codejockie) [reply imports/plugins/core/dashboard/client/templates/shop/settings/settings.js]: Yes, that would be case. I would changing that soon, need to remove that line.

**Comment by pmn4** [comment]
thanks @codejockie!
