### PR TITLE
Fix getSlug imports

### LINKED ISSUE #4696: [bug] Running fresh installation steps results in a console error concerning migration
## Issue Description
Under a fresh installation with no existing DB, running the installation steps produce a console error. 

This does not impede the application from running. 

```
reaction_1            | 14:42:05.383Z ERROR Reaction:
reaction_1            |   Error while migrating TypeError: getSlug is not a function
reaction_1            |       at shops.forEach.shop (imports/plugins/core/versions/server/migrations/7_add_shop_slugs_to_schema.js:19:24)
reaction_1            |       at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
reaction_1            |       at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
reaction_1            |       at Object.up (imports/plugins/core/versions/server/migrations/7_add_shop_slugs_to_schema.js:17:11)
reaction_1            |       at migrate (packages/percolate_migrations.js:233:25)
reaction_1            |       at Object.Migrations._migrateTo (packages/percolate_migrations.js:253:7)
reaction_1            |       at Object.Migrations.migrateTo (packages/percolate_migrations.js:167:10)
reaction_1            |       at Hooks.Events.add (imports/plugins/core/versions/server/startup.js:31:18)
reaction_1            |       at /opt/reaction/src/node_modules/@reactioncommerce/hooks/dist/main.js:71:14
reaction_1            |       at Array.reduce (<anonymous>)
reaction_1            |       at Object.Hooks.Events.run (/opt/reaction/src/node_modules/@reactioncommerce/hooks/dist/main.js:70:22)
reaction_1            |       at Object.init (imports/plugins/core/core/server/Reaction/core.js:75:18)
reaction_1            |       at startup (imports/plugins/core/core/server/startup/index.js:38:12)
reaction_1            |       at Function.time (/opt/reaction/src/.meteor/local/build/programs/server/profile.js:309:28)
reaction_1            |       at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:427:13
reaction_1            |       at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:472:5
reaction_1            |
reaction_1            | Note: you are using a pure-JavaScript implementation of bcrypt.
reaction_1            | While this implementation will work correctly, it is known to be
reaction_1            | approximately three times slower than the native implementation.
reaction_1            | In order to use the native implementation instead, run
reaction_1            |
reaction_1            |   meteor npm install --save bcrypt
reaction_1            |
reaction_1            | in the root directory of your application.
reaction_1            | /home/node/.meteor/packages/promise/.0.11.1.1vczms8.mxi5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
reaction_1            |       throw error;
reaction_1            |       ^
reaction_1            |
reaction_1            | TypeError: Migrations.unlock is not a function
reaction_1            |     at Hooks.Events.add (imports/plugins/core/versions/server/startup.js:35:18)
reaction_1            |     at /opt/reaction/src/node_modules/@reactioncommerce/hooks/dist/main.js:71:14
reaction_1            |     at Array.reduce (<anonymous>)
reaction_1            |     at Object.Hooks.Events.run (/opt/reaction/src/node_modules/@reactioncommerce/hooks/dist/main.js:70:22)
reaction_1            |     at Object.init (imports/plugins/core/core/server/Reaction/core.js:75:18)
reaction_1            |     at startup (imports/plugins/core/core/server/startup/index.js:38:12)
reaction_1            |     at Function.time (/opt/reaction/src/.meteor/local/build/programs/server/profile.js:309:28)
reaction_1            |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:427:13
reaction_1            |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:472:5
reaction_1            |     at Function.run (/opt/reaction/src/.meteor/local/build/programs/server/profile.js:510:12)
reaction_1            |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:470:11
reaction_1            | => Exited with code: 1
```

## Steps to Reproduce

1. Have a clean development environment (no relating docker containers/networks) + clean `git clone` of this repository
2. Run `docker-compose up`
3. Watch console, will appear shortly

### Versions
Reaction 2.0.0-rc.2

### PR DESCRIPTION
**Pull request by aldeed**
Resolves #4696   
Impact: **minor**  
Type: **bugfix**

## Issue
Error during migration. See linked issue.

## Solution
When getSlug was moved, some imports were not updated. Updated them.

## Breaking changes
None

## Testing
1. Set DB migration version to 6 or lower and start the app, or start the app on a fresh database.
2. Verify that no errors occur during the migration on startup

### CODE REVIEW

File: imports/plugins/core/versions/server/migrations/7_add_shop_slugs_to_schema.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ Migrations.add({
     // Loop through all shops creating slugs and creating merchant shop objects
     shops.forEach((shop) => {
       // create slug from shop name
-      const shopSlug = getSlug(shop.name);
+      const shopSlug = slugify(shop.name);
```
Comment (aldeed) [inline imports/plugins/core/versions/server/migrations/7_add_shop_slugs_to_schema.js]: This is the fix. Everything else is extra prevention for migration errors that I saw while testing, but that aren't very likely in the real world.
