### PR TITLE
Fix Errors importing exported product data 

### LINKED ISSUE #2480: Errors importing exported product data
### Expected behavior
Data exported from Reaction should be able to be imported back in

### Actual Behavior
Receive multiple errors on startup:
```
09:24:51.626Z  WARN Reaction: Error while importing to Products: After applying the update to the document {_id: "y9kZzcJsr6NrehXHd" , ...}, the (immutable) field '_id' was found to have been altered to _id: "viTbFMsLzPEgWetQE"
```
Data loaded is partial and causes the app to crash

### Steps to Reproduce the Behavior
Replace your `Products.json` with the following file: https://slack-files.com/T027FB1A3-F5XTT7TT9-e36ac40cfe

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: react-milestone-57
Docker: 17.03.1-ce
```

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2480 

### Steps to test
1. Sign in as admin
1. Add some products
1. Export the Products and Tags to a `Products.json` and `Tags.json` respectively
1. Replace the Products.json and `Tags.json` in `/private/data` with the exported files
1. Restart the application.
1. Observe that terminal throws no import errors as the application starts

### CODE REVIEW

File: server/api/core/import.js [hunk 1]
```diff
@@ -226,6 +226,10 @@ Import.buffer = function (collection) {
  * * Update the variant.
  */
 Import.product = function (key, product) {
+  // If product has an _id, we use it to look up the product before
+  // updating the product so as to avoid trying to change the _id
+  // which is immutable.
+  if (product._id && !key._id) key._id = product._id;
```
Comment (awadesmoline) [inline server/api/core/import.js]: @zenweasel Fixed
