### PR TITLE
Hide option panel for Merchant Shops

### LINKED ISSUE #3246: Hide options card on Shop panel for Merchant Shops
### Expected behavior

Merchant shops should not have the ability to set shop options 
These include (all in the options card):
- [ ] Exchange rates 
- [ ]  Google Client Ids and passwords

### Actual behavior

Merchant shops can change these settings since card is visible to them

### Steps to reproduce the behavior

- Log in as merchant shop
- On the sidebar click on `shops` icon 
- Open options card/panel
- Change the provided fields and save

### Versions
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.0
Reaction: 1.5.5
Reaction branch: master
Docker: 17.03.1-ce

### PR DESCRIPTION
**Pull request by joykare**
Resolves #3246 

### How to test
- Log in as merchant shop
- On the sidebar click on shops icon
- Notice option card is not visible to merchant shop admins

### CODE REVIEW

File: imports/plugins/core/dashboard/client/templates/shop/settings/settings.js [hunk 1]
```diff
@@ -154,7 +154,12 @@ Template.shopSettings.helpers({
     }).addressBook;
     return address[0];
   },
-  showAppSwitch() {
+  showAppSwitch(template) {
```
Comment (spencern) [inline imports/plugins/core/dashboard/client/templates/shop/settings/settings.js]: Should this be something that's in the registry?

**Comment by spencern** [comment]
eslint issue is resolved in master. Dependency issue is not displayed in bitHound, not sure what it's complaining about.
