### PR TITLE
Fix for variant option not updating when edited

### LINKED ISSUE #2582: Option name does not change when edited
### Expected behavior
When you change the option title (not the label) it should change elsewhere

### Actual Behavior
It does not change unless you delete the existing contents and then click away and then replace it.
basic_t-shirt

### Steps to Reproduce the Behavior
1. Login as admin
1. Create a new product
1. Set the Variant label
1. Change title, label, quantity and price.
1. Observe that the option title shown does not change but remains "Untitled Option" even when you publish

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.0
Reaction branch: development
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by foladipo**
Resolves #2582 

This PR fixes a bug with creating options for product variants. Previously, editing an option did not update parts of the UI. This PR fixes that bug.

### Testing steps
* Log in as admin.
* Open the panel for editing a product.
* Create a new variant option and try to edit its `option` or `price` form field. Immediately you hit `Enter`, click elsewhere on the page or hit `Tab`, the UI is updated with the text or price you added to the form field.

### CODE REVIEW

File: imports/plugins/included/product-variant/client/templates/products/productDetail/variants/variantForm/childVariant.js [hunk 1]
```diff
@@ -49,9 +49,11 @@ Template.childVariantForm.helpers({
   Icon() {
     return Components.Icon;
   },
+
```
Comment (zenweasel) [inline imports/plugins/included/product-variant/client/templates/products/productDetail/variants/variantForm/childVariant.js]: Can we not add in these line breaks for no reason?

**Comment by zenweasel** [comment]
@foladipo So this is an example of where we want to make sure and loop back on these PR's quickly. Let's try to make the one change I requested and get this merged? You should almost always prioritize dealing with PR feedback over almost anything.

**Comment by foladipo** [comment]
So sorry for the delay @zenweasel . I've now cleaned out the unnecessary line breaks and pushed the update.
