### PR TITLE
Fix broken marketplace orders dashboard

### LINKED ISSUE #2758: Marketplace orders dashboard broken
### Expected behavior

 - Can select multiple orders

### Actual Behavior

 - Cannot select multiple orders (Code missing due to merge issue)

### Steps to Reproduce the Behavior

- Make order
- Open orders dashboard and try select an order
- Observe that it doesn't happen

### Reaction Version
Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.5.0
Reaction branch: marketplace

### PR DESCRIPTION
**Pull request by kieha**
Resolves #2758 

Marketplace orders dashboard was broken, caused by the order filtering PR that was merged that had some code missing. This restores things back to order (pun intended 🤓).

### How to test

- Clone this branch
- Have at least 2 orders
- Visit orders dashboard
- Test it out: select orders, set shipping statuses, capture payments
- Observe that everything works as before

### CODE REVIEW

**Comment by joykare** [comment]
Back to normal 💯  :1st_place_medal:

**Comment by joykare** [comment]
@spencern **Urgent**  Fix to broken order dashboard due to earlier merge

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 1]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+  packedShippingStatus = (selectedOrders, status) => {
+    let isNotPicked = 0;
+    let isNotPacked = 0;
+    let isPacked = 0;
+    let ordersToRegress = 0;
+    const whichFalseState = shippingStates.picked;
+
+    selectedOrders.forEach((order) => {
+      // check if the order(s) are in this state already or in one of the previous states
+      if (order.shipping[0].workflow.status === "new") {
```
[the remark this answers is not in the document]
Comment (spencern) [reply imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: If we're going to leave this in for now, you could clean it up fairly easily with:
`const orderWorkflow = order.shipping[0].workflow.status;` and compare against that rather than using the longer version every time.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 2]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+  }
+
+  labeledShippingStatus = (selectedOrders, status) => {
+    let isNotPacked = 0;
+    let isNotLabeled = 0;
+    let isLabeled = 0;
+    let ordersToRegress = 0;
+    let whichFalseState = "";
+
+    selectedOrders.forEach((order) => {
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: I've seen this bit of code 3 times now. Would like to have some comments and documentation explaining what the difference is between these very similar functions.

All the comments I've made on previous ones apply here too.

Additionally, worth adding a `TODO` task to write some helper functionality that can reduce the repetition and increase readability.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 3]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+      // check if the order(s) are in this state already or in the previous state
+      if (order.shipping[0].workflow.status === "new") {
+        isNotPicked++;
+      } else if (order.shipping[0].workflow.status === "coreOrderWorkflow/picked") {
+        isPicked++;
+      } else {
+        // check if the selected order(s) are being regressed back to this state
+        if (order.shipping[0].workflow.workflow.includes("coreOrderWorkflow/picked")) {
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: Would like to have more comments explaining the different directions these `if..else if.. else` blocks can take.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 4]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+      }
+    });
+    const selectedOrders = this.state.orders.filter((order) => {
+      return selectedOrdersIds.includes(order._id);
+    });
+
+    let orderCount = 0;
+
+    selectedOrders.forEach((order) => {
+      Meteor.call("orders/approvePayment", order, (err) => {
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: We should be batching these and performing a single method call rather than making a call for each order

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 5]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+        if (err) {
+          this.setState({
+            isLoading: {
+              capturePayment: false
+            }
+          });
+          Alerts.toast(`An error occured while approving the payment: ${err}`, "error");
+        } else {
+          Meteor.call("orders/capturePayments", order._id, (error) => {
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: Batch.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 6]
```diff
@@ -194,6 +260,397 @@ class OrderDashboardContainer extends Component {
...
+              this.setState({
+                isLoading: {
+                  capturePayment: false
+                }
+              });
+              Alerts.toast(`An error occured while capturing the payment: ${error}`, "error");
+            }
+
+            if (order.workflow.status === "new") {
+              Meteor.call("workflow/pushOrderWorkflow", "coreOrderWorkflow", "processing", order);
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: This should probably be performed on the server and not as an additional call from the client.

**Comment by kieha** [comment]
@spencern all your comments on this are valid, i.e. this code is not marketplace ready. 

However, I'd like to point out that this is code that was already in marketplace, brought in from the [bulk actions PR](https://github.com/reactioncommerce/reaction/pull/2613), that got omitted when the [order filtering PR](https://github.com/reactioncommerce/reaction/pull/2688) was merged into marketplace, thus breaking stuff on the orders dashboard. I had already created an issue to make this code marketplace ready [here](https://github.com/reactioncommerce/reaction/issues/2724) that'll fix most of the issues with this.

That being said, I'll put comments and TODO blocks where they explain what the code at several places does and what needs to be done to make this marketplace ready.

**Comment by spencern** [comment]
@kieha 
That was my understanding of this code as well, but I didn't remember seeing some of this to this point. We can merge this to fix the outstanding issues that were caused by the omission, but I needed to make note of the future incompatibility somewhere. 

I appreciate you taking the time to add TODOs and updating the issue #2724. It feels like updating the order code to be marketplace compatible is starting to become an epic in itself.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 7]
```diff
@@ -75,13 +83,52 @@ class OrderDashboardContainer extends Component {
       selectedItems: [],
       orders: props.orders,
       multipleSelect: false,
+      shipping: {
+        picked: false,
```
[the remark this answers is not in the document]
Comment (kieha) [reply imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: This part is not backend code to manage the shipping states. These are just state variables I'm using on the front end to change the UI (background color and icons on the lists) depending on what the user has clicked. 

E.g. before an order's status is set to `picked`, the state variable is as above, i.e. `this.state.shipping.picked = false`, which gives it this view (the order is not picked so the `picked` list item has a blue-ish background color and a circle as the icon):

screen shot 2017-08-30 at 2 59 09 am

After the order is set to `picked`, the state variable changes to `this.state.shipping.picked = true`, which triggers the UI change to this (the order has now been picked, this the list item background color and icon changes as below):

screen shot 2017-08-30 at 3 01 24 am

**Comment by kieha** [comment]
@spencern I believe I've addressed most, if not all of the concerns raised around this PR by adding comments and TODO blocks around code that needs to be changed. I've also referenced this PR in this issue #2724.

You could take a second look at it.

**Comment by spencern** [comment]
@kieha I'll take a look shortly.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (spencern) [reply imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: I realize this, but doesn't this marry the front-end to our current backend workflow?

What happens if this frontend is used to manage a non-standard workflow?

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 8]
```diff
@@ -194,6 +270,468 @@ class OrderDashboardContainer extends Component {
...
+        }
+      });
+    });
+  }
+
+  displayAlert = (selectedOrders, status, options) => {
+    // capitalize the first letter of the shipping status passed in
+    // e.g. 'shipped' becomes 'Shipped'.
+    // status[0].toUpperCase() capitalizes the first letter of the string
+    // status.substr(1).toLowerCase() converts every other letter to lower case
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: As an example for why this is important, but also why I'm an idiot, I was thinking that status[0] was the first item in an array during the last review not reading close enough to see that it's actually just pulling the first letter of the string.  Thanks for adding these comments.

**Comment by kieha** [comment]
@spencern from your explanation,  I've added TODOs for the boolean shipping states as well. 
I think this is good to go now.

I'm starting on #2724 ASAP.

File: imports/plugins/core/orders/client/containers/orderDashboardContainer.js [hunk 9]
```diff
@@ -83,13 +83,15 @@ class OrderDashboardContainer extends Component {
...
       multipleSelect: false,
+      // TODO: model this with the assumption that there may be different stages to workflows
       shipping: {
         picked: false,
         packed: false,
         labeled: false,
         shipped: false
       },
       renderFlowList: false,
+      // TODO: model this with the assumption that there may be different stages to workflows
```
Comment (spencern) [inline imports/plugins/core/orders/client/containers/orderDashboardContainer.js]: This is the right assumption 👍
