### PR TITLE
fix: Can't re-send shop manager invite to existing non-activated user

### LINKED ISSUE #5176: Can't re-send shop manager invite to existing non-activated user
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After sending an invite to a non-registered e-mail, a new user is created for them with a token to be used to set their password. An e-mail invite is then sent with a URL containing this token.

However, if you want to re-send an invitation to this same person, the `accounts/inviteShopMember` will see an existing account for this e-mail, not checking whether it was activated or not. This means that no new "set password" token will be sent, and the user will be promoted to shop manager (which it already was), as if it was an already active account.

## Steps to Reproduce
1. Invite an e-mail that doesn't have an account to be a shop manager.
2. Receive an invitation e-mail. Delete it "by mistake".
3. Invite this same e-mail again with the intent of sending a new invitation.
4. Receive an e-mail saying that you were promoted to shop manager... But you can't log into your account since you don't have a password.

## Possible Solution
In the `accounts/inviteShopMember` logic, if an account already exists for the e-mail address but isn't activated yet, generate a new token and send a new invite.

### PR DESCRIPTION
**Pull request by loan-laux**
Resolves #5176  
Impact: **major**  
Type: **bugfix**

## Issue
After sending a shop manager invite to a non-registered e-mail, a new user is created for them with a token to be used to set their password. An e-mail invite is then sent with a URL containing this token.

However, if you want to re-send an invitation to this same person, the `accounts/inviteShopMember` will see an existing account for this e-mail, not checking whether it was activated or not. This means that no new "set password" token will be sent, and the user will be promoted to shop manager (which it already was), as if it was an already active account.

## Solution
In the `accounts/inviteShopMember` logic, if an account already exists for the e-mail address but isn't activated yet, generate a new token and send a new invite.

Also, add some confirmation dialogs in case an e-mail already exists, whether it's activated or not.

## Breaking changes
None.

## Testing
1. In the `Accounts` page of the operator, invite an e-mail address that's already registered and activated.
2. See a dialog asking you if you want to promote this existing user to shop manager.
3. Invite an e-mail that's never been used for an account before.
4. Receive invite on that e-mail. Delete it "by mistake".
5. Re-invite this same e-mail again in an attempt to send a new invite.
6. See a dialog asking you if you want to send a new invitation. Click yes.
7. Receive a new invitation with a new token.
8. Click on the button in the e-mail, see the "set password" form.

### CODE REVIEW

File: imports/plugins/core/accounts/client/components/adminInviteForm.js [hunk 1]
```diff
@@ -67,30 +91,33 @@ class AdminInviteForm extends Component {
       );
     }
 
+    const matchingAccount = getUserByEmail(email);
+    const isEmailVerified = matchingAccount &&
+      matchingAccount.emails &&
+      matchingAccount.emails[0] &&
+      matchingAccount.emails[0].verified;
```
Comment (aldeed) [inline imports/plugins/core/accounts/client/components/adminInviteForm.js]: Rather than using index 0, it would be more correct to find the item where `obj.address === email`

File: imports/plugins/core/accounts/server/methods/inviteShopMember.js [hunk 2]
```diff
@@ -69,15 +69,19 @@ export default function inviteShopMember(options) {
   const currentUser = Meteor.user();
   const currentUserName = getCurrentUserName(currentUser);
   const user = Meteor.users.findOne({ "emails.address": email });
+  const isEmailVerified = user && user.emails && user.emails[0] && user.emails[0].verified;
```
Comment (aldeed) [inline imports/plugins/core/accounts/server/methods/inviteShopMember.js]: Rather than using index 0, it would be more correct to find the item where `obj.address === email`

**Comment by aldeed** [comment]
Ping @loan-laux

**Comment by loan-laux** [comment]
Sorry @aldeed, I was on vacation and just came back today. I'll implement the requested changes today.

**Comment by loan-laux** [comment]
@aldeed Let me know if this fix is what you had in mind.

File: imports/plugins/core/accounts/client/components/adminInviteForm.js [hunk 3]
```diff
@@ -53,6 +53,30 @@ class AdminInviteForm extends Component {
...
+      } else if (error.reason === "cannot directly invite owner") {
+        messageKey = "admin.groupsInvite.inviteOwnerError";
+      } else if (error.reason === "cannot invite to group") {
+        messageKey = "admin.groupsInvite.cannotInvite";
+      } else if (error.reason === "Need to set a username or email") {
+        messageKey = "admin.groupsInvite.NeedToSetUsernameOrEmail";
+      } else {
+        messageKey = "admin.groupsInvite.errorSendingInvite";
+      }
+      ReactionAlerts.add(error.reason, "danger", Object.assign({}, alertOptions, { i18nKey: messageKey }));
```
Comment (willopez) [inline imports/plugins/core/accounts/client/components/adminInviteForm.js]: @loan-laux there is an eslint error and code error on this line, `alertOptions` is not defined. FYI @aldeed

File: imports/plugins/core/accounts/server/methods/inviteShopMember.js [hunk 4]
```diff
@@ -89,14 +98,19 @@ export default function inviteShopMember(options) {
...
-      name,
-      groupId
-    });
-    // set token to be used for first login for the new account
+    // There could be an existing user with an invite still pending (not activated).
+    // We create a new account only if there's no pending invite.
+    if (!user) {
+      // The user does not already exist, we need to create a new account
+      userId = MeteorAccounts.createUser({
+        profile: {invited: true},
```
Comment (willopez) [inline imports/plugins/core/accounts/server/methods/inviteShopMember.js]: @loan-laux lint errors here as well. suggested change: `{invited: true}` => `{ invited: true }`

**Comment by loan-laux** [comment]
Good catch @willopez, thanks!

**Comment by willopez** [comment]
integration tests failing due to this know issue: https://github.com/reactioncommerce/reaction/issues/5246. 

I have verified all tests pass locally.

**Comment by willopez** [comment]
@loan-laux thank you for your contribution 👍
